[build]
  command = "yarn install --ignore-engines && yarn build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  YARN_VERSION = "1.22.22"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
